name: CI

on:
  workflow_dispatch:

env:
  PASSWORD: ${{ secrets.MYPSW }}

jobs:
  passord:
    runs-on: ubuntu latest
    env:
      PASSWORD: ${{ secrets.MYPSW }}
    steps: 
      - name: Execute script
        run: php connect.php
        env:
          PASSWORD: ${{ secrets.MYPSW }}
