name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu latest
    steps: 
      - name: Execute script
        env:
          PASSWORD: ${{ secrets.MYPSW }}
        run: php connect.php
